# IMPORTANT{ File automatically generated by Django CLI tool }
# The purpose of this is file is define the default app config

from django.apps import AppConfig


class StoreConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'store'
